### ISSUE TITLE
Missing directus email (sender)

### ISSUE THREAD

**Issue by WellingGuzman** [directus/directus-docker#15]
Originally reported: https://github.com/directus/directus/issues/1530
Title: Swiftmailer validation refuses RFC 2822 compliant e-mails

## Version Info
  - Directus docker 6.3
  - PHP version: 7.1.2

## Steps to Reproduce
 1.  Run a directus docker instance
 2.  (Optional: Create a new user)
 3.  Log out
 4. Press the reset password button
 5. Observe the network call to /forgot-password fail with an error 500 

## Logs or Screenshots

```
{
  "code": 0,
  "class": "Swift_RfcComplianceException",
  "message": "Address in mailbox given [{{directus_email}}] does not comply with RFC 2822, 3.6.2.",
  "file": "/var/www/html/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Mime/Headers/MailboxHeader.php",
  "line": 345, [...]
```

E-mail was checked and was rfc 2822 compliant. It raises another issue, if swiftmailer is going to reject non rfc compliant e-mails they should prob not be allowed at signup

**Comment by GeeWizWow** [comment]
@WellingGuzman Thanks, I'll track progress here then.

**Comment by Froelund** [comment]
I just tried to reproduce, and the error also appears in the log `docker exec directus less /var/www/html/api/logs/2017-05-31.log`
```
Stack trace:
#0 /var/www/html/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Mime/Headers/MailboxHeader.php(263): Swift_Mime_Headers_MailboxHeader->_assertValidAddress('{{directus_emai...')
#1 /var/www/html/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Mime/Headers/MailboxHeader.php(106): Swift_Mime_Headers_MailboxHeader->normalizeMailboxes(Array)
#2 /var/www/html/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Mime/Headers/MailboxHeader.php(63): Swift_Mime_Headers_MailboxHeader->setNameAddresses(Array)
#3 /var/www/html/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Mime/SimpleMimeEntity.php(592): Swift_Mime_Headers_MailboxHeader->setFieldBodyModel(Array)
#4 /var/www/html/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Mime/SimpleMessage.php(219): Swift_Mime_SimpleMimeEntity->_setHeaderFieldModel('From', Array)
#5 /var/www/html/api/core/Directus/Mail/Mail.php(60): Swift_Mime_SimpleMessage->setFrom('{{directus_emai...')
#6 /var/www/html/api/api.php(756): Directus\Mail\Mail::send('mail/reset-pass...', Array, Object(Closure))
#7 [internal function]: {closure}()
#8 /var/www/html/vendor/slim/slim/Slim/Route.php(436): call_user_func_array(Object(Closure), Array)
#9 /var/www/html/vendor/slim/slim/Slim/Slim.php(1305): Slim\Route->dispatch()
#10 /var/www/html/vendor/slim/slim/Slim/Middleware/Flash.php(85): Slim\Slim->call()
#11 /var/www/html/vendor/slim/slim/Slim/Middleware/MethodOverride.php(92): Slim\Middleware\Flash->call()
#12 /var/www/html/api/core/Directus/Slim/CorsMiddleware.php(22): Slim\Middleware\MethodOverride->call()
#13 /var/www/html/vendor/slim/slim/Slim/Slim.php(1254): Directus\Slim\CorsMiddleware->call()
#14 /var/www/html/api/core/Directus/Application/Application.php(74): Slim\Slim->run()
#15 /var/www/html/api/api.php(1888): Directus\Application\Application->run()
#16 {main}
```

**Comment by WellingGuzman** [comment]
I juggled this too early, but in fact directus doesn't have a way to specify this option through the command line, so any way I will keep this ticket here, and I will fix this on the command line module.

**Comment by WellingGuzman** [comment]
Partially fixed by: https://github.com/directus/directus/commit/2aded9d198a4cda36dcdaf75d9b14edb4b681d77

**Comment by WellingGuzman** [comment]
Hey @Froelund we could include a new env variable to be set as the sender email which will fallback to the directus user email if not set.

This will be tagged in Directus 6.4 RC2

**Comment by Froelund** [comment]
We do actually have an environment variable that specifies the sending email:
https://github.com/directus/directus-docker/blob/master/directus-base-layer/usr/local/bin/run-directus#L6
We should probably update the documentation for the container though.

**Comment by WellingGuzman** [comment]
Exactly, just in case that email will be different than the actual user email.
