### ISSUE TITLE
Fatal error: Allowed memory size exhausted

### ISSUE THREAD

**Issue by ftdube** [directus/directus-docker#23]
When loading http://localhost:8080 for the first time after setuping the docker container (using procedure mentioned in https://github.com/directus/directus-docker/issues/20), on Docker for Windows, I get the following content instead of the CMS :

Warning: array_key_exists() expects parameter 2 to be array, integer given in /var/www/html/api/api.php on line 76

Warning: array_key_exists() expects parameter 2 to be array, integer given in /var/www/html/api/api.php on line 80

Fatal error: Allowed memory size of 134217728 bytes exhausted (tried to allocate 20480 bytes) in /var/www/html/api/core/Directus/Auth/Provider.php on line 53

Fatal error: Allowed memory size of 134217728 bytes exhausted (tried to allocate 20480 bytes) in /var/www/html/api/core/Directus/Exception/ExceptionHandler.php on line 68

**Comment by WellingGuzman** [comment]
@ftdube which Directus version are you using?

**Comment by WellingGuzman** [comment]
It seems like you don't have the `configuration.php` file, if you are using Directus 6.3, I will fix this issue on Directus 6.3.x to be aware of missing `configuration.php` file on this matter at least.

**Comment by ftdube** [comment]
I believe I was using 6.3 since 6.4 was still in RC at the time.

**Comment by WellingGuzman** [comment]
Hey @ftdube, 6.4 was in stable release, the readme was outdated.

Please try both again and let us know, it should've been fixed by now I updated both image

**Comment by WellingGuzman** [comment]
I will close this until it can be replicated again
