### ISSUE TITLE
Use a tag per patch version

### ISSUE THREAD

**Issue by wittwerch** [directus/directus-docker#27]
Currently all images including patch releases from Directus 6.4 are tagged as 6.4. 
It would be great if you could create a tag per patch version so we can properly reference the image and don't get a newer one.

**Comment by WellingGuzman** [comment]
Thanks @wittwerch, I will be work on that one.

**Comment by WellingGuzman** [comment]
Hey @wittwerch I have created patch version tags for 6.4.x the last two versions

Ref: https://hub.docker.com/r/getdirectus/directus/tags/

**Comment by wittwerch** [comment]
Awesome, thx!
