### ISSUE TITLE
DIRECTUS_ADMIN_TOKEN

### ISSUE THREAD

**Issue by cgarnier** [directus/directus-docker#28]
Could you add a env to set the admin token ?
Thanks,

**Comment by WellingGuzman** [comment]
Hey @cgarnier, How are you going to use this? or what are you referring to?

The user access token, It's a token created randomly per user.

**Comment by cgarnier** [comment]
I need it to use the api.

**Comment by WellingGuzman** [comment]
I mean, how are you going to use the env. you can get the user token using the `POST api/1.1/auth/request-token` and send `email:<email>&password:<password>`

**Comment by tiptronic** [comment]
Sorry to bring this up again, but it seems I can't get the admin-token:
If I send a POST request to: 
http://directus.test/api/1.1/auth/request-token?email=my%40example.com&password=12345

I always get
```json
{
  "success": false,
  "error": {
    "message": "Incorrect email or password"
  }
}
```
the user exists!
Anything I'm missing here?

**Comment by tiptronic** [comment]
Nevermind... I found the problem:
To send the request, I have to add 

`Content-Type:application/x-www-form-urlencoded` 

to the headers

**Comment by lastlink** [comment]
I'm able to retrieve the admin token. However this isn't working for any other normal users. I can log them in directly to the directus website, but trying to retrieve their token gives the same error as everyone else. 

`
{
  "success": false,
  "error": {
    "message": "Incorrect email or password"
  }
}
`

 ## api request-token:


```
POST https://cms.funktechno.com/pwalistdev/api/1.1/auth/request-token HTTP/1.1
Content-Type: application/x-www-form-urlencoded

email={{useremail}}&password={{userpw}}`
```

**Comment by WellingGuzman** [comment]
@lastlink this may be related to https://github.com/directus/directus/issues/2099 fixed by https://github.com/directus/directus/commit/164c09556d60bb0b4b72f4610537c54e0a0d01e6

This happens when the user has not token.

---
As we are not setting the admin token as environment either unless there's a good example on why, I will re-open it.

**Comment by linonetwo** [comment]
@tiptronic That helps. I was using Raw JSON to POST and always get "Incorrect email or password", switching to `x-www-form-urlencoded` solved this.
