### ISSUE TITLE
Add CORS headers to API response

### ISSUE THREAD

**Issue by simondegheselle** [directus/directus-docker#32]

**Comment by WellingGuzman** [comment]
Hey @simondegheselle, have you tried using the `cors` settings in `configuration.php`

Or are you asking to an option to enable from the dockerfile?

**Comment by simondegheselle** [comment]
Hi @WellingGuzman, it worked using a local directus git checkout and modifying the `configuration.php` file, thanks!

**Comment by WellingGuzman** [comment]
Awesome! Glad to hear!
