### ISSUE TITLE
The current 6.4 image seems buggy

### ISSUE THREAD

**Issue by filidorwiese** [directus/directus-docker#40]
Hi! Maybe it's me and I just need more guidance. But after starting a fresh mysql and directus 6.4 docker container, as instructed in the readme, I found the installation of Directus quite buggy.

For example, when trying to create a new user I get this error:

```
Error
Error: Uncaught TypeError: Cannot read property 'data' of undefined
File: http://localhost:8080/app/router.js?bust=27c055438973a56a34d5ec88248c3493
Line:647
```

When creating a new table, I don't get any option to change the table settings, add fields to the table or anything anywhere. It all seems pretty empty and non-functional.

Is it me?

**Comment by WellingGuzman** [comment]
Hey @filidorwiese Thanks for the report, we had a major bug on the `6.4.7` release and we fixed it on `6.4.8` with https://github.com/directus/directus/commit/51f8cbcbc5369f0625f9d30c7cd84d08ccb16829.

The docker image is being currently build right now.

Ref: https://hub.docker.com/r/getdirectus/directus/builds/
