### ISSUE TITLE
Docker Container Behind Reverse Proxy Redirects Improperly

### ISSUE THREAD

**Issue by davetrux** [directus/directus-docker#5]
We have an nginx reverse proxy in front of our Docker server. We want our Directus container to be visible at https://oursite.com/cms/.  But the Directus container wants the app to be in the root and redirects incorrectly for first login, instead of https://oursite.com/cms/login.php it is redirecting to https://oursite.com/login.php. Is there some sort of environment variable we have to set? We are using automation for deployments so it's not feasible to go into the containers by hand after deployment and edit them. Is there some configuration we are missing?

Trux

**Comment by Froelund** [comment]
You could run directus as a sub-domain instead. https://api.oursite.com/

**Comment by davetrux** [comment]
We did that as a workaround and it's working, but we really need subdirectories. Our solution is using automation and we can't add DNS entries like we do subdirectories.

**Comment by WellingGuzman** [comment]
Hey @davetrux, it's not supported but this seems to be something useful to have.

I will take a look into it.

**Comment by WellingGuzman** [comment]
hey @davetrux I added a variable where you can change the subdirectory configuration, I don't know if this will solve your problem but it's probably one step closer to it, I'd like you to help me find the solution you are looking for.

Commit: https://github.com/directus/directus-docker/commit/c7c2bfae7c51748c5acbf7acb5ec987450c61107

**Comment by davetrux** [comment]
I cloned the repo on our build server. I edited the makefile to change the version number of directus-base-layer to be v0.0.8 which is what the directus 6.3 Dockerfile expects. I then executed the makefile. Then I built an image from the directus 6.3 Dockerfile. 

Then, I added this to our test docker-compose file:

- DIRECTUS_PATH=/directus

It still doesn't redirect properly. Did I miss something?

**Comment by Froelund** [comment]
@davetrux Is there any reason why you want to build Directus yourself?
I just tested it with below, and didn't work for me either.
```
# Start mysql
docker run -e MYSQL_ROOT_PASSWORD=password -e MYSQL_DATABASE=directus -e MYSQL_USER=directus \
          -e MYSQL_PASSWORD=directus --name mysql -d mysql:5.5

# Start directus
docker run --link mysql:mysql -p 8080:8080 --name directus -e DIRECTUS_PATH=/directus -d getdirectus/directus:6.3
```

**Comment by davetrux** [comment]
I had originally tried it without building it myself and it didn't work, so
I decided to build it myself in case there was some reason that I could not
see that kept me from getting the change.

**Comment by WellingGuzman** [comment]
Hey @davetrux,

Are you looking for something like this:

```
docker run --link mysql:mysql -p 8080:8080 --name directus -e DIRECTUS_ROOT=/root/path/directus -e DIRECTUS_PATH=/cms -d getdirectus/directus:6.3
```

So Directus downloads into `/root/www/cms` instead of `/var/www/html` where the localhost point to `/root/www` and directus will be hosted as subdirectory in `cms` (localhost/cms)?

**Comment by davetrux** [comment]
That may work. My problem is that I have to use a reverse proxy to map a url (that looks like a subdirectory) to a container running on a port that is only open internally. There is no way for me to tell Directus that it should handle the url when redirecting.

**Comment by WellingGuzman** [comment]
Hey @davetrux,

I understand a bit more your issue now, so the actual url (container) won't match the proxy url. Couldn't this resolved by match the same subdirectory in directus as the reverse proxy?

I'd love to get this nailed down in some way.
